// Seeds baseline data after a schema push/reset. Safe to re-run (upserts by
// a fixed id). Run via `pnpm db:seed` (from repo root) or `node prisma/seed.js`
// from apps/api.
//
// Listing-page URLs below were verified live: each one was fetched and had a
// repeating listing pattern detected, and its pagination scheme was confirmed
// by checking that page 2 returns different rows than page 1. Do not assume the
// `/category/<x>/` convention for a new source without checking it — most
// Nepal government sites do not use it, and a wrong URL fails as a confusing
// "could not detect a listing pattern" rather than an obvious 404.
// Sources with enabled:false have hosts that did not respond at all; their URLs
// are kept so they can be re-enabled once reachable.
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const SOURCES = [
  {
    id: '00000000-0000-0000-0000-00000000001e',
    name: 'Commission for the Investigation of Abuse of Authority (CIAA)',
    baseUrl: 'https://ciaa.gov.np',
    noticeListUrl: null,
    newsListUrl: null,
    pressReleaseListUrl: 'https://ciaa.gov.np/pressreleaseCategory/charge',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000021',
    name: 'Department of Customs',
    baseUrl: 'https://www.customs.gov.np',
    noticeListUrl: null,
    newsListUrl: null,
    pressReleaseListUrl: null,
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000023',
    name: 'Department of Foreign Employment',
    baseUrl: 'https://dofe.gov.np',
    noticeListUrl: 'https://dofe.gov.np/category/notices',
    newsListUrl: 'https://dofe.gov.np/category/news/',
    pressReleaseListUrl: null,
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-00000000001f',
    name: 'Department of Immigration',
    baseUrl: 'https://www.immigration.gov.np',
    noticeListUrl: 'https://immigration.gov.np/news-notices',
    newsListUrl: 'https://immigration.gov.np/news-notices',
    pressReleaseListUrl: null,
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000022',
    name: 'Department of Roads',
    baseUrl: 'https://www.dor.gov.np',
    noticeListUrl: 'https://www.dor.gov.np/home/notices',
    newsListUrl: null,
    pressReleaseListUrl: null,
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-00000000001d',
    name: 'Election Commission Nepal',
    baseUrl: 'https://election.gov.np',
    noticeListUrl: 'https://election.gov.np/category/notice/',
    newsListUrl: 'https://election.gov.np/category/news/',
    pressReleaseListUrl: 'https://election.gov.np/category/press-release/',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '5c9a3c6e-f3b9-4a03-8d6d-e52c96a58ffa',
    name: 'Homae affai',
    baseUrl: 'https://moha.gov.np/en',
    noticeListUrl: 'https://moha.gov.np/en/page/notice',
    newsListUrl: 'https://moha.gov.np/en/page/news',
    pressReleaseListUrl: null,
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000020',
    name: 'Inland Revenue Department',
    baseUrl: 'https://ird.gov.np',
    noticeListUrl: 'https://ird.gov.np/category/notice/',
    newsListUrl: null,
    pressReleaseListUrl: 'https://ird.gov.np/category/pressrelease/',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000004',
    name: 'Kathmandu University (KU)',
    baseUrl: 'https://ku.edu.np',
    noticeListUrl: 'https://ku.edu.np/notice',
    newsListUrl: null,
    pressReleaseListUrl: null,
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-00000000000d',
    name: 'Ministry of Agriculture and Livestock Development',
    baseUrl: 'https://moald.gov.np',
    noticeListUrl: 'https://moald.gov.np/category/notice/',
    newsListUrl: null,
    pressReleaseListUrl: 'https://moald.gov.np/category/press-release/',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-00000000001a',
    name: 'Ministry of Communication and Information Technology',
    baseUrl: 'https://mocit.gov.np',
    noticeListUrl: 'https://mocit.gov.np/category/notice/',
    newsListUrl: 'https://mocit.gov.np/category/news/',
    pressReleaseListUrl: null,
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000019',
    name: 'Ministry of Culture, Tourism and Civil Aviation',
    baseUrl: 'https://tourism.gov.np',
    noticeListUrl: 'https://tourism.gov.np/category/notice/',
    newsListUrl: 'https://tourism.gov.np/category/News/',
    pressReleaseListUrl: 'https://tourism.gov.np/category/press-release/',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-00000000000c',
    name: 'Ministry of Defence',
    baseUrl: 'https://mod.gov.np',
    noticeListUrl: 'https://mod.gov.np/category/notice/',
    newsListUrl: 'https://mod.gov.np/category/news/',
    pressReleaseListUrl: 'https://mod.gov.np/category/press-release/',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000006',
    name: 'Ministry of Education, Science & Technology',
    baseUrl: 'https://moest.gov.np',
    noticeListUrl: 'https://moest.gov.np/category/notice/',
    newsListUrl: 'https://moest.gov.np/category/news/',
    pressReleaseListUrl: 'https://moest.gov.np/category/press-release/',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000013',
    name: 'Ministry of Energy, Water Resources and Irrigation',
    baseUrl: 'https://moewri.gov.np',
    noticeListUrl: 'https://moewri.gov.np/category/notice-board',
    newsListUrl: null,
    pressReleaseListUrl: 'https://moewri.gov.np/category/press-release/',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-00000000000f',
    name: 'Ministry of Federal Affairs and General Administration',
    baseUrl: 'https://mofaga.gov.np',
    noticeListUrl: 'https://mofaga.gov.np/notices',
    newsListUrl: null,
    pressReleaseListUrl: null,
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000008',
    name: 'Ministry of Finance',
    baseUrl: 'https://mof.gov.np',
    noticeListUrl: 'https://mof.gov.np/category/notices/',
    newsListUrl: null,
    pressReleaseListUrl: 'https://mof.gov.np/category/press-release-budget/',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000001',
    name: 'Ministry of Foreign Affairs (MOFA)',
    baseUrl: 'https://mofa.gov.np',
    noticeListUrl: 'https://mofa.gov.np/category/information/',
    newsListUrl: 'https://mofa.gov.np/category/news/',
    pressReleaseListUrl: 'https://mofa.gov.np/category/presscategory/',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000014',
    name: 'Ministry of Forests and Environment',
    baseUrl: 'https://mofe.gov.np',
    noticeListUrl: 'https://mofe.gov.np/category/notice-news/',
    newsListUrl: 'https://mofe.gov.np/category/news/',
    pressReleaseListUrl: 'https://mofe.gov.np/category/press-release/',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000009',
    name: 'Ministry of Health and Population',
    baseUrl: 'https://mohp.gov.np',
    noticeListUrl: null,
    newsListUrl: 'https://mohp.gov.np/category/latest-news/',
    pressReleaseListUrl: 'https://mohp.gov.np/category/pressrelease',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000005',
    name: 'Ministry of Home Affairs',
    baseUrl: 'https://moha.gov.np',
    noticeListUrl: null,
    newsListUrl: 'https://moha.gov.np/page/news',
    pressReleaseListUrl: 'http://moha.gov.np/page/press-release',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000010',
    name: 'Ministry of Industry, Commerce and Supplies',
    baseUrl: 'https://moics.gov.np',
    noticeListUrl: 'https://moics.gov.np/category/notice/',
    newsListUrl: 'https://moics.gov.np/category/news/',
    pressReleaseListUrl: 'https://moics.gov.np/category/press-release/',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-00000000000e',
    name: 'Ministry of Labour, Employment and Social Security',
    baseUrl: 'https://mole.gov.np',
    noticeListUrl: 'https://mole.gov.np/category/notice/',
    newsListUrl: 'https://mole.gov.np/category/news/',
    pressReleaseListUrl: 'https://mole.gov.np/category/press-release/',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000016',
    name: 'Ministry of Land Management, Cooperatives and Poverty Alleviation',
    baseUrl: 'https://molcpa.gov.np',
    noticeListUrl: 'https://molcpa.gov.np/category/notices/',
    newsListUrl: 'https://molcpa.gov.np/category/news/',
    pressReleaseListUrl: 'https://molcpa.gov.np/category/press-disc-/',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-00000000001b',
    name: 'Ministry of Law, Justice and Parliamentary Affairs',
    baseUrl: 'https://moljpa.gov.np',
    noticeListUrl: null,
    newsListUrl: null,
    pressReleaseListUrl: null,
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000011',
    name: 'Ministry of Physical Infrastructure and Transport',
    baseUrl: 'https://mopit.gov.np',
    noticeListUrl: 'https://mopit.gov.np/category/self-publishing-notices/',
    newsListUrl: 'https://mopit.gov.np/category/news/',
    pressReleaseListUrl: 'https://mopit.gov.np/category/press-release/',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000012',
    name: 'Ministry of Urban Development',
    baseUrl: 'https://mud.gov.np',
    noticeListUrl: 'https://mud.gov.np/category/notice/',
    newsListUrl: 'https://mud.gov.np/category/news/',
    pressReleaseListUrl: null,
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000015',
    name: 'Ministry of Water Supply',
    baseUrl: 'https://mowss.gov.np',
    noticeListUrl: 'https://mowss.gov.np/category/notice/',
    newsListUrl: 'https://mowss.gov.np/category/news/',
    pressReleaseListUrl: null,
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000017',
    name: 'Ministry of Women, Children and Senior Citizens',
    baseUrl: 'https://mowcsc.gov.np',
    noticeListUrl: 'https://mowcsc.gov.np/category/notice/',
    newsListUrl: null,
    pressReleaseListUrl: 'https://mowcsc.gov.np/category/press-release',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000018',
    name: 'Ministry of Youth and Sports',
    baseUrl: 'https://moys.gov.np',
    noticeListUrl: 'https://moys.gov.np/pages/notifications-20/',
    newsListUrl: null,
    pressReleaseListUrl: null,
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000027',
    name: 'National Vigilance Center',
    baseUrl: 'https://nvc.gov.np',
    noticeListUrl: 'https://nvc.gov.np/category/notice/',
    newsListUrl: null,
    pressReleaseListUrl: null,
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '678e3e00-7e97-4380-ab30-2dc9d3b2e59c',
    name: 'nea',
    baseUrl: 'https://nea.org.np/en/category/news',
    noticeListUrl: 'https://nea.org.np/en/category/news',
    newsListUrl: null,
    pressReleaseListUrl: null,
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000002',
    name: 'Nepal Rastra Bank (NRB)',
    baseUrl: 'https://www.nrb.org.np',
    noticeListUrl: 'https://www.nrb.org.np/category/notices/',
    newsListUrl: null,
    pressReleaseListUrl: null,
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000026',
    name: 'Nepal Telecommunications Authority (NTA)',
    baseUrl: 'https://www.nta.gov.np',
    noticeListUrl: 'https://www.nta.gov.np/category/notice/',
    newsListUrl: 'https://www.nta.gov.np/category/news/',
    pressReleaseListUrl: null,
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-00000000001c',
    name: 'Office of the Auditor General',
    baseUrl: 'https://oagnep.gov.np',
    noticeListUrl: 'https://oagnep.gov.np/category/notice/',
    newsListUrl: null,
    pressReleaseListUrl: null,
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000024',
    name: 'Office of the Company Registrar',
    baseUrl: 'https://www.ocr.gov.np',
    noticeListUrl: 'https://www.ocr.gov.np/category/notice/',
    newsListUrl: null,
    pressReleaseListUrl: null,
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: false,
  },
  {
    id: '00000000-0000-0000-0000-00000000000b',
    name: 'Office of the President',
    baseUrl: 'https://www.presidentofnepal.gov.np',
    noticeListUrl: 'https://www.presidentofnepal.gov.np/category/notice/',
    newsListUrl: null,
    pressReleaseListUrl: 'https://www.presidentofnepal.gov.np/category/press-release/',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-00000000000a',
    name: 'Office of the Prime Minister and Council of Ministers',
    baseUrl: 'https://opmcm.gov.np',
    noticeListUrl: 'https://opmcm.gov.np/category/notice/',
    newsListUrl: null,
    pressReleaseListUrl: 'https://opmcm.gov.np/category/press-release/',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000007',
    name: 'Public Service Commission (Lok Sewa Aayog)',
    baseUrl: 'https://psc.gov.np',
    noticeListUrl: 'https://psc.gov.np/category/notice/',
    newsListUrl: null,
    pressReleaseListUrl: 'https://psc.gov.np/category/press-release/',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000025',
    name: 'Securities Board of Nepal (SEBON)',
    baseUrl: 'https://www.sebon.gov.np',
    noticeListUrl: 'https://www.sebon.gov.np/notices',
    newsListUrl: 'https://www.sebon.gov.np/news',
    pressReleaseListUrl: 'https://www.sebon.gov.np/press-releases',
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000003',
    name: 'Tribhuvan University (TU)',
    baseUrl: 'https://tu.edu.np',
    noticeListUrl: 'https://tu.edu.np/notices',
    newsListUrl: 'https://tu.edu.np/news',
    pressReleaseListUrl: null,
    paginationType: 'QUERY_PARAM',
    paginationParam: 'page',
    enabled: true,
  },
];

async function main() {
  for (const src of SOURCES) {
    const source = await prisma.scrapeSource.upsert({
      where: { id: src.id },
      update: {
        pressReleaseListUrl: src.pressReleaseListUrl,
        newsListUrl: src.newsListUrl,
        noticeListUrl: src.noticeListUrl,
        paginationType: src.paginationType,
        paginationParam: src.paginationParam,
        // A listing URL change invalidates the cached extraction schema that
        // was detected against the old page; clearing forces re-detection.
        noticeSchema: null,
        newsSchema: null,
        pressReleaseSchema: null,
      },
      create: {
        id: src.id,
        name: src.name,
        baseUrl: src.baseUrl,
        noticeListUrl: src.noticeListUrl,
        newsListUrl: src.newsListUrl,
        pressReleaseListUrl: src.pressReleaseListUrl,
        paginationType: src.paginationType,
        paginationParam: src.paginationParam,
        enabled: src.enabled,
        maxPages: 10,
      },
    });
    console.log(`Seeded: ${source.name}`);
  }
  console.log(`\nDone — ${SOURCES.length} sources seeded.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
