import { Notice, User, RagDocument, ScrapingSource, AlertRule, Activity } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    username: "admin",
    email: "admin@govnotice.np",
    role: "admin",
    createdAt: "2024-01-15T00:00:00Z",
    lastLogin: "2026-06-02T08:30:00Z",
    status: "active",
  },
  {
    id: "2",
    username: "ramesh_sharma",
    email: "ramesh@example.com",
    role: "user",
    createdAt: "2024-03-20T00:00:00Z",
    lastLogin: "2026-06-01T14:22:00Z",
    status: "active",
  },
  {
    id: "3",
    username: "sita_devi",
    email: "sita@example.com",
    role: "user",
    createdAt: "2024-06-10T00:00:00Z",
    lastLogin: "2026-05-28T09:15:00Z",
    status: "active",
  },
  {
    id: "4",
    username: "krishna_gc",
    email: "krishna@example.com",
    role: "user",
    createdAt: "2025-01-05T00:00:00Z",
    lastLogin: "2026-05-30T16:45:00Z",
    status: "inactive",
  },
]

export const mockNotices: Notice[] = [
  {
    id: "n1",
    title: "Nepal Public Service Commission - Section Officer Exam 2082",
    description: "Applications are invited for the post of Section Officer (Non-Technical) under Nepal Public Service Commission for the year 2082.",
    content: "The Nepal Public Service Commission invites applications from eligible Nepali citizens for the competitive examination for Section Officer (Non-Technical) posts. Candidates must possess a Master's degree from a recognized university. The examination will be conducted in two phases: written examination and interview. Application deadline: Shrawan 15, 2082.",
    category: "exams",
    organization: "Nepal Public Service Commission",
    publishedAt: "2026-05-28T10:00:00Z",
    updatedAt: "2026-05-28T10:00:00Z",
    deadline: "2026-07-30T23:59:00Z",
    priority: "high",
    views: 15420,
    author: "NPSC Secretary",
    status: "published",
  },
  {
    id: "n2",
    title: "Ministry of Education - Teacher Recruitment Drive 2082",
    description: "Vacancy announcement for 2,500 permanent teacher positions across all 7 provinces.",
    content: "The Ministry of Education announces 2,500 permanent teaching positions at primary, lower-secondary, and secondary levels. Positions are distributed across all seven provinces. Candidates must have completed Teacher Service Commission certification. Applications accepted through the online portal only.",
    category: "vacancies",
    organization: "Ministry of Education",
    publishedAt: "2026-05-25T08:00:00Z",
    updatedAt: "2026-05-26T12:00:00Z",
    deadline: "2026-06-30T23:59:00Z",
    priority: "high",
    views: 28340,
    author: "Education Ministry",
    status: "published",
  },
  {
    id: "n3",
    title: "Road Division Office - Highway Construction Tender",
    description: "Sealed bids invited for the construction of 45km highway section in Province 5.",
    content: "The Road Division Office, Butwal invites sealed bids from eligible contractors for the construction of a 45km highway section connecting Butwal to Palpa. The estimated cost is NRs. 4.5 billion. Bidders must have completed at least 2 similar projects in the past 5 years. Bid security: NRs. 50 million.",
    category: "tenders",
    organization: "Road Division Office, Butwal",
    publishedAt: "2026-05-20T09:00:00Z",
    updatedAt: "2026-05-20T09:00:00Z",
    deadline: "2026-06-20T17:00:00Z",
    priority: "normal",
    views: 4560,
    author: "Chief Engineer",
    status: "published",
  },
  {
    id: "n4",
    title: "Nepal Rastra Bank - New Monetary Policy Guidelines",
    description: "Updated monetary policy framework for fiscal year 2082/83 effective immediately.",
    content: "Nepal Rastra Bank has issued updated monetary policy guidelines for fiscal year 2082/83. Key changes include: revised interest rate corridors, new lending limits for commercial banks, updated capital adequacy requirements, and enhanced digital payment regulations. All banking institutions must comply within 30 days.",
    category: "policy",
    organization: "Nepal Rastra Bank",
    publishedAt: "2026-05-15T06:00:00Z",
    updatedAt: "2026-05-18T14:00:00Z",
    priority: "high",
    views: 8920,
    author: "NRB Governor",
    status: "published",
  },
  {
    id: "n5",
    title: "Kathmandu Metropolitan City - Water Supply Schedule Change",
    description: "Revised water distribution schedule for Kathmandu Valley effective from Jestha 20.",
    content: "Due to reduced water levels in Melamchi and Sundarijal sources, Kathmandu Metropolitan City announces a revised water distribution schedule. Ward numbers 1-16 will receive water on odd days, wards 17-32 on even days. Duration: 4 hours per supply day. Citizens are requested to store water accordingly.",
    category: "announcements",
    organization: "Kathmandu Metropolitan City",
    publishedAt: "2026-06-01T07:00:00Z",
    updatedAt: "2026-06-01T07:00:00Z",
    priority: "normal",
    views: 12100,
    author: "KMC Water Division",
    status: "published",
  },
  {
    id: "n6",
    title: "Department of Immigration - Online Passport Renewal System",
    description: "New online passport renewal system launched. In-person visits no longer required for renewals.",
    content: "The Department of Immigration is pleased to announce the launch of a fully digital passport renewal system. Citizens with passports expiring within 6 months can now complete the entire renewal process online. Documents required: citizenship certificate scan, current passport scan, recent photograph. Processing time: 7-10 working days.",
    category: "announcements",
    organization: "Department of Immigration",
    publishedAt: "2026-05-30T11:00:00Z",
    updatedAt: "2026-05-30T11:00:00Z",
    priority: "normal",
    views: 34500,
    author: "Director General",
    status: "published",
  },
  {
    id: "n7",
    title: "Nepal Electricity Authority - Solar Energy Subsidy Program",
    description: "Government subsidy of up to 50% on rooftop solar installations for residential buildings.",
    content: "NEA announces a new subsidy program for rooftop solar panel installations. Residential buildings can receive up to 50% subsidy (max NRs. 200,000) on solar systems up to 5kW capacity. Applications accepted at all NEA district offices. Program valid until the allocated budget of NRs. 5 billion is exhausted.",
    category: "policy",
    organization: "Nepal Electricity Authority",
    publishedAt: "2026-05-22T10:00:00Z",
    updatedAt: "2026-05-22T10:00:00Z",
    deadline: "2026-12-31T23:59:00Z",
    priority: "normal",
    views: 19200,
    author: "NEA Managing Director",
    status: "published",
  },
  {
    id: "n8",
    title: "Tribhuvan University - PhD Program Admission 2082",
    description: "Applications open for PhD programs across 12 faculties for academic session 2082.",
    content: "Tribhuvan University invites applications for its PhD programs across 12 faculties including Management, Science & Technology, Humanities, Education, and Engineering. Applicants must hold an MPhil or Master's degree with minimum 55% marks. Entrance examination scheduled for Bhadra 1, 2082.",
    category: "exams",
    organization: "Tribhuvan University",
    publishedAt: "2026-05-18T09:00:00Z",
    updatedAt: "2026-05-19T15:00:00Z",
    deadline: "2026-07-15T23:59:00Z",
    priority: "normal",
    views: 7800,
    author: "TU Registrar",
    status: "published",
  },
  {
    id: "n9",
    title: "Nepal Army - Officer Cadet Recruitment 2082",
    description: "Recruitment notice for 150 Officer Cadet positions in Nepal Army.",
    content: "Nepal Army Headquarters announces recruitment for 150 Officer Cadet positions. Eligibility: Nepali citizens aged 18-24, Bachelor's degree minimum, physically fit. Selection process includes written exam, physical fitness test, medical examination, and interview. Training period: 12 months at Nepal Military Academy, Kharipati.",
    category: "vacancies",
    organization: "Nepal Army Headquarters",
    publishedAt: "2026-05-12T08:00:00Z",
    updatedAt: "2026-05-12T08:00:00Z",
    deadline: "2026-06-15T17:00:00Z",
    priority: "high",
    views: 22100,
    author: "Adjutant General",
    status: "published",
  },
  {
    id: "n10",
    title: "Department of Roads - Bridge Construction Tender (Karnali Province)",
    description: "International competitive bidding for construction of 3 major bridges in Karnali Province.",
    content: "Department of Roads invites international competitive bids for construction of three reinforced concrete bridges in Karnali Province. Total estimated cost: NRs. 8.2 billion. Joint ventures are encouraged. Pre-qualification deadline: Ashadh 30, 2082. Funded by Asian Development Bank.",
    category: "tenders",
    organization: "Department of Roads",
    publishedAt: "2026-05-10T10:00:00Z",
    updatedAt: "2026-05-11T09:00:00Z",
    deadline: "2026-07-14T17:00:00Z",
    priority: "normal",
    views: 3200,
    author: "Director General",
    status: "published",
  },
]

export const mockDocuments: RagDocument[] = [
  {
    id: "d1",
    title: "Nepal Constitution 2072 (Full Text)",
    category: "Legal",
    uploadedAt: "2025-12-01T10:00:00Z",
    fileSize: "4.2 MB",
    viewCount: 8940,
    summary: "Complete text of the Constitution of Nepal 2072 including all amendments up to 2082.",
    format: "pdf",
  },
  {
    id: "d2",
    title: "Civil Service Act 2049 (Amended 2079)",
    category: "Legal",
    uploadedAt: "2025-11-15T08:00:00Z",
    fileSize: "1.8 MB",
    viewCount: 5620,
    summary: "The Civil Service Act governing appointment, promotion, and conduct of civil servants in Nepal.",
    format: "pdf",
  },
  {
    id: "d3",
    title: "National Education Policy 2076",
    category: "Education",
    uploadedAt: "2026-01-20T09:00:00Z",
    fileSize: "2.1 MB",
    viewCount: 3450,
    summary: "Comprehensive national education policy framework covering basic to higher education.",
    format: "pdf",
  },
  {
    id: "d4",
    title: "Public Procurement Guidelines 2081",
    category: "Procurement",
    uploadedAt: "2026-03-10T11:00:00Z",
    fileSize: "3.5 MB",
    viewCount: 6780,
    summary: "Updated public procurement guidelines for all government entities including e-bidding procedures.",
    format: "pdf",
  },
  {
    id: "d5",
    title: "Budget Speech FY 2082/83",
    category: "Finance",
    uploadedAt: "2026-05-29T06:00:00Z",
    fileSize: "890 KB",
    viewCount: 12300,
    summary: "Annual budget speech delivered by the Finance Minister for fiscal year 2082/83.",
    format: "pdf",
  },
  {
    id: "d6",
    title: "IT Policy 2077 (Digital Nepal Framework)",
    category: "Technology",
    uploadedAt: "2026-02-14T10:00:00Z",
    fileSize: "1.2 MB",
    viewCount: 4100,
    summary: "National IT policy framework outlining digital transformation goals and strategies.",
    format: "pdf",
  },
]

export const mockScrapingSources: ScrapingSource[] = [
  {
    id: "s1",
    name: "Nepal Gazette Online",
    url: "https://rajpatra.dop.gov.np",
    frequency: "Daily",
    category: "policy",
    status: "active",
    lastRun: "2026-06-02T06:00:00Z",
    itemsScraped: 1245,
  },
  {
    id: "s2",
    name: "Public Procurement Portal",
    url: "https://bolpatra.gov.np",
    frequency: "Every 6 hours",
    category: "tenders",
    status: "active",
    lastRun: "2026-06-02T08:00:00Z",
    itemsScraped: 3420,
  },
  {
    id: "s3",
    name: "PSC Official Website",
    url: "https://psc.gov.np",
    frequency: "Daily",
    category: "exams",
    status: "active",
    lastRun: "2026-06-01T22:00:00Z",
    itemsScraped: 890,
  },
  {
    id: "s4",
    name: "MoE Job Portal",
    url: "https://education.gov.np/vacancies",
    frequency: "Every 12 hours",
    category: "vacancies",
    status: "error",
    lastRun: "2026-05-30T12:00:00Z",
    itemsScraped: 456,
  },
]

export const mockAlertRules: AlertRule[] = [
  {
    id: "a1",
    userId: "2",
    type: "keyword",
    name: "Section Officer Updates",
    conditions: ["section officer", "lok sewa", "PSC"],
    enabled: true,
    createdAt: "2026-04-01T10:00:00Z",
    matchCount: 12,
  },
  {
    id: "a2",
    userId: "2",
    type: "category",
    name: "All Exam Notices",
    conditions: ["exams"],
    enabled: true,
    createdAt: "2026-03-15T08:00:00Z",
    matchCount: 34,
  },
  {
    id: "a3",
    userId: "2",
    type: "organization",
    name: "NRB Policy Updates",
    conditions: ["Nepal Rastra Bank"],
    enabled: false,
    createdAt: "2026-05-01T14:00:00Z",
    matchCount: 5,
  },
]

export const mockActivities: Activity[] = [
  { id: "act1", userId: "2", type: "view", description: "Viewed 'Section Officer Exam 2082'", timestamp: "2026-06-02T08:15:00Z", relatedId: "n1" },
  { id: "act2", userId: "2", type: "save", description: "Saved 'Teacher Recruitment Drive 2082'", timestamp: "2026-06-01T16:30:00Z", relatedId: "n2" },
  { id: "act3", userId: "2", type: "search", description: "Searched for 'tender kathmandu'", timestamp: "2026-06-01T14:20:00Z" },
  { id: "act4", userId: "2", type: "alert", description: "Alert triggered: Section Officer Updates", timestamp: "2026-05-28T10:05:00Z", relatedId: "a1" },
  { id: "act5", userId: "2", type: "document", description: "Accessed 'Nepal Constitution 2072'", timestamp: "2026-05-27T11:00:00Z", relatedId: "d1" },
  { id: "act6", userId: "2", type: "view", description: "Viewed 'Online Passport Renewal System'", timestamp: "2026-05-26T09:45:00Z", relatedId: "n6" },
]

export const categories = [
  { id: "exams", label: "Exams", count: 2 },
  { id: "vacancies", label: "Vacancies", count: 2 },
  { id: "tenders", label: "Tenders", count: 2 },
  { id: "policy", label: "Policy", count: 2 },
  { id: "announcements", label: "Announcements", count: 2 },
] as const
